// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5AXodtFwjk4BttVNu2VKf1LIRx10KI84',
    appId: '1:773729323612:web:b17cacca7d55caeab7f499',
    messagingSenderId: '773729323612',
    projectId: 'edicion-limitada',
    authDomain: 'edicion-limitada.firebaseapp.com',
    storageBucket: 'edicion-limitada.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKNdqi3jHIwaP9lIJ5-EcK9iVwut9HJjg',
    appId: '1:773729323612:android:b2295b78072cd99db7f499',
    messagingSenderId: '773729323612',
    projectId: 'edicion-limitada',
    storageBucket: 'edicion-limitada.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoyuy1fCLTRbI6q5ycILd43cUVxiw9qPo',
    appId: '1:773729323612:ios:55d454d43d0f589ab7f499',
    messagingSenderId: '773729323612',
    projectId: 'edicion-limitada',
    storageBucket: 'edicion-limitada.firebasestorage.app',
    iosBundleId: 'com.example.edicionLimitada',
  );
}
